# [mongodb]
# mongodb.anuragaws.shop

# [redis]
# redis.anuragaws.shop

# [mysql]
# mysql.anuragaws.shop

# [rabbitmq]
# rabbitmq.anuragaws.shop

# [cart]
# cart.anuragaws.shop

# [catalogue]
# catalogue.anuragaws.shop

# [user]
# user.anuragaws.shop

# [shipping]
# shipping.anuragaws.shop

# [payment]
# payment.anuragaws.shop

# [frontend]
# frontend.anuragaws.shop

# [backend]
# [all:vars]
# ansible_user=ec2-user
# ansible_password=DevOps321

# [local]
# localhost 